version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5254:80"
      - "7186:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=YourSecurePassword123!
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=dddtemplate;Username=postgres;Password=postgres
      - Redis__ConnectionString=redis:6379
    volumes:
      - ./certificates:/https:ro
    depends_on:
      - postgres
      - redis
    networks:
      - ddd-network

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dddtemplate
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ddd-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ddd-network

networks:
  ddd-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: